# Generated by Django 4.1 on 2023-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NAME", models.TextField(blank=True, default="", null=True)),
                ("BIRTHDAY", models.DateTimeField(default="2000-01-01", null=True)),
                ("DEPTNO", models.CharField(default="", max_length=6, null=True)),
                ("EMP_TYPE", models.CharField(default="", max_length=30, null=True)),
                ("TEL", models.CharField(default="", max_length=15, null=True)),
                ("HOBBY", models.CharField(default="", max_length=30, null=True)),
                ("PAY", models.IntegerField(blank=True, default=0, null=True)),
                ("POSITION", models.CharField(default="", max_length=30, null=True)),
                ("PEMPNO", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
