# Generated by Django 4.1 on 2023-11-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "EMPNO",
                    models.CharField(blank=True, default=None, max_length=8, null=True),
                ),
                (
                    "NAME",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("BIRTHDAY", models.DateField(blank=True, default=None, null=True)),
                (
                    "DEPTNO",
                    models.CharField(blank=True, default=None, max_length=6, null=True),
                ),
                (
                    "EMP_TYPE",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "TEL",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                (
                    "HOBBY",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("PAY", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "POSITION",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("PEMPNO", models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
